### ISSUE TITLE
Internal Server Error loading image from Flickr

### ISSUE THREAD

**Issue by cgansen** [smartchicago/connect-chicago-locator#23]
Received via exception_notifier:

```
An OpenURI::HTTPError occurred in location#showImage:

  500 Internal Server Error
  /usr/local/lib/ruby/1.9.1/open-uri.rb:346:in `open_http'


-------------------------------
Request:
-------------------------------

  * URL       : http://locations.weconnectchicago.org/location/woodson-regional-library-9525-s-halsted-street/image.jpg
  * IP address: 12.189.171.162
  * Parameters: {"controller"=>"location", "action"=>"showImage", "id"=>"woodson-regional-library-9525-s-halsted-street"}
  * Rails root: /app
  * Timestamp : 2013-05-08 11:16:40 -0500

-------------------------------
Session:
-------------------------------

  * session id: "0588d881cdae2e5f121decfbc50369b6"
  * data: {"session_id"=>"0588d881cdae2e5f121decfbc50369b6",
   "_csrf_token"=>"9rZg55TqOweeDdcGPpkCKHuW1eXa596x/zepanumuF0="}

-------------------------------
Environment:
-------------------------------

  * HTTP_ACCEPT                                    : */*
  * HTTP_ACCEPT_CHARSET                            : ISO-8859-1,utf-8;q=0.7,*;q=0.3
  * HTTP_ACCEPT_ENCODING                           : gzip,deflate,sdch
  * HTTP_ACCEPT_LANGUAGE                           : en-US,en;q=0.8
  * HTTP_CONNECTION                                : close
  * HTTP_COOKIE                                    : km_ai=%2BEjJjtuuB0mtjZpOsQoxVRZPFww%3D; km_lv=x; qtrans_cookie_test=qTranslate+Cookie+Test; __utma=200911144.942267803.1367937550.1367937550.1367937550.1; __utmc=200911144; __utmz=200911144.1367937550.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none); _TechLocator_session=BAh7B0kiD3Nlc3Npb25faWQGOgZFRkkiJTA1ODhkODgxY2RhZTJlNWYxMjFkZWNmYmM1MDM2OWI2BjsAVEkiEF9jc3JmX3Rva2VuBjsARkkiMTlyWmc1NVRxT3dlZURkY0dQcGtDS0h1VzFlWGE1OTZ4L3plcGFudW11RjA9BjsARg%3D%3D--bbb4e95f0b62eed8d7e960b94c23feac84efe921; km_uq=; __atuvc=100%7C18%2C56%7C19; __utma=73820687.1080696096.1367338888.1367958671.1368028452.9; __utmb=73820687.19.10.1368028452; __utmc=73820687; __utmz=73820687.1367338888.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none); kvcd=1368029766817; km_vs=1
  * HTTP_HOST                                      : locations.weconnectchicago.org
  * HTTP_REFERER                                   : http://locations.weconnectchicago.org/location/woodson-regional-library-9525-s-halsted-street
  * HTTP_USER_AGENT                                : Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.31 (KHTML, like Gecko) Chrome/26.0.1410.64 Safari/537.31
  * HTTP_VERSION                                   : HTTP/1.0
  * HTTP_X_FORWARDED_FOR                           : 12.189.171.162
  * HTTP_X_REAL_IP                                 : 12.189.171.162
  * HTTP_X_REQUEST_START                           : 1368029800277
  * ORIGINAL_FULLPATH                              : /location/woodson-regional-library-9525-s-halsted-street/image.jpg
  * PATH_INFO                                      : /location/woodson-regional-library-9525-s-halsted-street/image.jpg
  * QUERY_STRING                                   :
  * REMOTE_ADDR                                    : 10.92.231.217
  * REQUEST_METHOD                                 : GET
  * REQUEST_PATH                                   : /location/woodson-regional-library-9525-s-halsted-street/image.jpg
  * REQUEST_URI                                    : /location/woodson-regional-library-9525-s-halsted-street/image.jpg
  * SCRIPT_NAME                                    :
  * SERVER_NAME                                    : locations.weconnectchicago.org
  * SERVER_PORT                                    : 80
  * SERVER_PROTOCOL                                : HTTP/1.0
  * SERVER_SOFTWARE                                : Unicorn 4.5.0
  * action_controller.instance                     : location#showImage
  * action_dispatch.backtrace_cleaner              : #<Rails::BacktraceCleaner:0x00000005306218>
  * action_dispatch.cookies                        : #<ActionDispatch::Cookies::CookieJar:0x000000065bebd0>
  * action_dispatch.logger                         : #<ActiveSupport::TaggedLogging:0x000000057225b8>
  * action_dispatch.parameter_filter               : [:password, :password_confirmation, /RAW_POST_DATA/]
  * action_dispatch.remote_ip                      : 12.189.171.162
  * action_dispatch.request.accepts                : [*/*]
  * action_dispatch.request.content_type           :
  * action_dispatch.request.formats                : [*/*]
  * action_dispatch.request.parameters             : {"controller"=>"location", "action"=>"showImage", "id"=>"woodson-regional-library-9525-s-halsted-street"}
  * action_dispatch.request.path_parameters        : {:controller=>"location", :action=>"showImage", :id=>"woodson-regional-library-9525-s-halsted-street"}
  * action_dispatch.request.query_parameters       : {}
  * action_dispatch.request.request_parameters     : {}
  * action_dispatch.request.unsigned_session_cookie: {"session_id"=>"0588d881cdae2e5f121decfbc50369b6", "_csrf_token"=>"9rZg55TqOweeDdcGPpkCKHuW1eXa596x/zepanumuF0="}
  * action_dispatch.request_id                     : f33061155babb0da786ecaaf94a2721c
  * action_dispatch.routes                         : #<ActionDispatch::Routing::RouteSet:0x0000000582e178>
  * action_dispatch.secret_token                   : 14fc65fcf2c8d6797dc2a67b82f17d10fbce20764e30c73d9607f3d9bf0e0d2ff801e14413ad028c2613fdd0041bcc9bb37d149ac99f0e47d3b185ddb62d1fd4
  * action_dispatch.show_detailed_exceptions       : false
  * action_dispatch.show_exceptions                : true
  * rack-cache.allow_reload                        : false
  * rack-cache.allow_revalidate                    : false
  * rack-cache.cache_key                           : Rack::Cache::Key
  * rack-cache.default_ttl                         : 0
  * rack-cache.entitystore                         : rails:/
  * rack-cache.ignore_headers                      : ["Set-Cookie"]
  * rack-cache.metastore                           : rails:/
  * rack-cache.private_headers                     : ["Authorization", "Cookie"]
  * rack-cache.storage                             : #<Rack::Cache::Storage:0x00000005743d80>
  * rack-cache.use_native_ttl                      : false
  * rack-cache.verbose                             : false
  * rack.errors                                    : #<IO:0x000000023064f0>
  * rack.input                                     : #<StringIO:0x000000030e7100>
  * rack.logger                                    : #<Logger:0x00000002f5d7f8>
  * rack.multiprocess                              : true
  * rack.multithread                               : false
  * rack.request.cookie_hash                       : {"km_ai"=>"+EjJjtuuB0mtjZpOsQoxVRZPFww=", "km_lv"=>"x", "qtrans_cookie_test"=>"qTranslate Cookie Test", "__utma"=>"200911144.942267803.1367937550.1367937550.1367937550.1", "__utmc"=>"200911144", "__utmz"=>"200911144.1367937550.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none)", "_TechLocator_session"=>"BAh7B0kiD3Nlc3Npb25faWQGOgZFRkkiJTA1ODhkODgxY2RhZTJlNWYxMjFkZWNmYmM1MDM2OWI2BjsAVEkiEF9jc3JmX3Rva2VuBjsARkkiMTlyWmc1NVRxT3dlZURkY0dQcGtDS0h1VzFlWGE1OTZ4L3plcGFudW11RjA9BjsARg==--bbb4e95f0b62eed8d7e960b94c23feac84efe921", "km_uq"=>"", "__atuvc"=>"100|18,56|19", "__utmb"=>"73820687.19.10.1368028452", "kvcd"=>"1368029766817", "km_vs"=>"1"}
  * rack.request.cookie_string                     : km_ai=%2BEjJjtuuB0mtjZpOsQoxVRZPFww%3D; km_lv=x; qtrans_cookie_test=qTranslate+Cookie+Test; __utma=200911144.942267803.1367937550.1367937550.1367937550.1; __utmc=200911144; __utmz=200911144.1367937550.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none); _TechLocator_session=BAh7B0kiD3Nlc3Npb25faWQGOgZFRkkiJTA1ODhkODgxY2RhZTJlNWYxMjFkZWNmYmM1MDM2OWI2BjsAVEkiEF9jc3JmX3Rva2VuBjsARkkiMTlyWmc1NVRxT3dlZURkY0dQcGtDS0h1VzFlWGE1OTZ4L3plcGFudW11RjA9BjsARg%3D%3D--bbb4e95f0b62eed8d7e960b94c23feac84efe921; km_uq=; __atuvc=100%7C18%2C56%7C19; __utma=73820687.1080696096.1367338888.1367958671.1368028452.9; __utmb=73820687.19.10.1368028452; __utmc=73820687; __utmz=73820687.1367338888.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none); kvcd=1368029766817; km_vs=1
  * rack.request.query_hash                        : {}
  * rack.request.query_string                      :
  * rack.run_once                                  : false
  * rack.session                                   : {"session_id"=>"0588d881cdae2e5f121decfbc50369b6", "_csrf_token"=>"9rZg55TqOweeDdcGPpkCKHuW1eXa596x/zepanumuF0="}
  * rack.session.options                           : {:path=>"/", :domain=>nil, :expire_after=>nil, :secure=>false, :httponly=>true, :defer=>false, :renew=>false, :secret=>"1e801ad5a1f68a7c49efb2f77f0d414039a51142627f1e50b5e1a9818ee5", :coder=>#<Rack::Session::Cookie::Base64::Marshal:0x00000005e057b8>, :id=>"0588d881cdae2e5f121decfbc50369b6"}
  * rack.url_scheme                                : http
  * rack.version                                   : [1, 1]
  * warden                                         : Warden::Proxy:53335240 @config={:default_scope=>:admin, :scope_defaults=>{}, :default_strategies=>{:admin=>[:rememberable, :database_authenticatable]}, :intercept_401=>false, :failure_app=>#<Devise::Delegator:0x000000052f9798>}
```

**Comment by cgansen** [comment]
Also:

```
An ArgumentError occurred in location#showImage:

  need api key
  vendor/bundle/ruby/1.9.1/gems/fusion_tables-0.4.1/lib/fusion_tables/client/fusion_tables.rb:34:in `sql_get'


-------------------------------
Request:
-------------------------------

  * URL       : http://locations.weconnectchicago.org/location/uptown-library-929-w-buena-avenue/image.jpg
  * IP address: 207.181.228.205
  * Parameters: {"controller"=>"location", "action"=>"showImage", "id"=>"uptown-library-929-w-buena-avenue"}
  * Rails root: /app
  * Timestamp : 2013-06-16 20:37:46 -0500
```
